Кітап (Kitap) атты класс құрыңыз. Бұл кластың атауы (atau) және авторы (avtory) деген екі атрибуты болуы керек.
init әдісін қолданып, кітап атауын және авторын инициализациялаңыз.
Класс ішінде кітап_туралы_мәлімет (kitap_turaly_malimet) атты әдіс жасаңыз. Бұл әдіс "Кітап: [Атауы], Авторы: [Авторы]" деген мәтінді консольға шығаруы керек.
Осы класстан бір нысан (объект) жасаңыз және кітап_туралы_мәлімет әдісін шақырыңыз.

In [1]:

class Kitap:
    def __init__(self, atau, avtory):
        self.atau = atau
        self.avtory = avtory
    def kitap_turaly_malimet(self):
        print(f"Кітап: {self.atau}, Авторы: {self.avtory}")

my_kitap = Kitap("Абай жолы", "М.Әуезов")

my_kitap.kitap_turaly_malimet()


Кітап: Абай жолы, Авторы: М.Әуезов


numpy кітапханасын np ретінде импорттаңыз.
1-ден 9-ға дейінгі (9-ды қоса алғанда) сандардан тұратын бір өлшемді NumPy массивін (arr_a) жасаңыз.
3x3 өлшемді (3 жол, 3 баған) сандардан тұратын екі өлшемді NumPy массивін (arr_b) жасаңыз. Мысалы, 1-ден 9-ға дейінгі сандарды пайдаланыңыз.
Әр массивтің өлшемін (.shape) және деректер түрін (.dtype) шығарыңыз.

In [2]:
import numpy as np

arr_a = np.arange(1, 10)
print("arr_a:", arr_a)
print("arr_a өлшемі:", arr_a.shape)
print("arr_a деректер түрі:", arr_a.dtype)


arr_b = np.arange(1, 10).reshape(3, 3)
print("\narr_b:\n", arr_b)
print("arr_b өлшемі:", arr_b.shape)
print("arr_b деректер түрі:", arr_b.dtype)


arr_a: [1 2 3 4 5 6 7 8 9]
arr_a өлшемі: (9,)
arr_a деректер түрі: int64

arr_b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_b өлшемі: (3, 3)
arr_b деректер түрі: int64


numpy-ді np ретінде импорттаңыз.
Кездейсоқ 5 бүтін саннан тұратын екі бір өлшемді NumPy массивін (vec1 және vec2) жасаңыз (мысалы, 1-ден 10-ға дейінгі).
Векторизацияны қолдана отырып (циклсіз):

Екі массивті қосыңыз (vec1 + vec2).
Әрбір элементтің квадратын есептеңіз (vec1 ** 2). vec1 массивінің орташа мәнін (.mean()) және ең үлкен мәнін (.max()) табыңыз.\
Барлық нәтижелерді консольға шығарыңыз.

In [ ]:
import numpy as np

vec1 = np.random.randint(1, 11, size=5)
vec2 = np.random.randint(1, 11, size=5)

print("vec1:", vec1)
print("vec2:", vec2)

sum_vec = vec1 + vec2
print("vec1 + vec2 =", sum_vec)

vec1_square = vec1 ** 2
print("vec1 элементтерінің квадраты =", vec1_square)

mean_vec1 = vec1.mean()
max_vec1 = vec1.max()
print("vec1 орташа мәні =", mean_vec1)
print("vec1 ең үлкен мәні =", max_vec1)
